fixed defaultActiveKey in driving time
portato-io/portatoapp pull request #204
Opened 2023-07-12 12:18 UTC by mAkeddar

Active tab was set by default to single trip. Changed it to routeInfo.type

2023-07-12 12:58 UTC, mischakolbe requested changes
More a question than anything, regarding the first time a user gets to this page..

2023-07-12 13:11 UTC, mAkeddar commented on src/Components/PageComponents/RecurrentTripContent.tsx
> -    console.log('JESUIS DANS RECURRENT TRIP');
Ahahah active debugging

2023-07-12 13:14 UTC, mAkeddar commented on src/Pages/Driver/enterDrivingTime.tsx
> +  const [activeTab, setActiveTab] = useState(routeInfo.type);
Mmmmh I see. 
It's because the initial state of routeInfo.type is an empty string. I should change it to single trip for the first time

2023-07-16 09:07 UTC, hugo2410 approved these changes

2023-07-16 09:07 UTC, merged