Changed the start, using form fields to check
portato-io/portatoapp pull request #228
Opened 2023-07-27 16:45 UTC by mAkeddar

Linked form to next button
Now use initialValues field to init the fields and remember the values
Check if there's an error to trigger either onFinish or onFinishFailed

WOOOOOOOOOOOOOOOOOOOOOW

2023-08-02 11:19 UTC, mischakolbe commented
When going back to the Drive Capacity screen the fields are incorrectly validated (capacity is selected, but shows as not filled out).

https://github.com/portato-io/portatoapp/assets/24309085/aa469f7a-9e5b-424a-8e37-e0a50169f96b

On the Send request screen for timing, it's allowed to continue, without specifying the time of day (sorry, the end of the video is irrelevant).

https://github.com/portato-io/portatoapp/assets/24309085/f436808d-7825-419c-bd1d-7a0546b9b7b0

2023-08-02 11:21 UTC, mischakolbe requested changes
Generally seems to implement this feature nicely! Only found the 3 mentioned issues:

- Drive capacity (going back to this screen validates incorrectly) -> See video
- Send timing (allowed to proceed without having entered a time of day) -> See video
- Would be great if we could default to "no selection" for the send request weight & size.

2023-08-05 05:40 UTC, hugo2410 approved these changes

2023-08-05 05:41 UTC, hugo2410 commented
Mischa's comment are fixed, all good for me

2023-08-05 05:41 UTC, merged